<?php if (!isset($_SESSION['USER_ID'])) : ?>

<?php else : ?>
    <div class="card">
        <div class="p-2 bd-highlight">
            <h2>Editar nombre</h2>
            <form action="updateServicio" method="POST">
                <div class="mb-3">
                    <select name="id_servicio_streaming" class="form-select">
                        <?php foreach ($servicios as $s) : ?>
                            <option value="<?= $s->id_servicio_streaming ?>"><?= $s->nombre ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="mb-3">
                    <input type="text" placeholder="Ingrese el servicio" name="nombre">
                </div>
                <input type="submit" value="Editar">
            </form>
        </div>
    <?php endif ?>
    </div>