<?php if (!isset($_SESSION['USER_ID'])) : ?>

<?php else : ?>
    <div class="card">
        <div class="p-2 bd-highlight">
            <h2>Editar nombre</h2>
            <form action="updatePeli" method="POST">
                <div class="mb-3">
                    <select name="id_pelicula" class="form-select">
                        <?php foreach ($peliculas as $pelicula) : ?>
                            <option value="<?= $pelicula->id_pelicula ?>"><?= $pelicula->nombre ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="mb-3">
    <input type="text" placeholder="Ingrese el nombre" name="nombre" class="form-control mb-3">
    <input type="text" placeholder="Ingrese el director" name="director" class="form-control mb-3">
    <select name="servicio_fk" class="form-control">
    <option value="" disabled selected>Seleccione un servicio</option>
        <?php foreach ($servicios as $s) : ?>
            <option value="<?php echo $s->id_servicio_streaming?>"><?php echo $s->nombre ?></option> 
        <?php endforeach; ?>
    </select>                    
    <label for="tipo">Tipo:</label>
    <select name="tipo" class="form-select ">
        <option value="Pelicula">Película</option>
        <option value="Serie">Serie</option>
        
    </select>

    <label for="genero">Género:</label>
    <select name="genero" class="form-select ">
    <option value="Accion">Acción</option>
    <option value="Aventura">Aventura</option>
    <option value="Comedia">Comedia</option>
    <option value="Drama">Drama</option>
    <option value="Ciencia ficcion">Ciencia Ficción</option>
    <option value="Fantasia">Fantasía</option>
    <option value="Terror">Terror</option>
    <option value="Documental">Documental</option>
    <option value="Otro">Otro</option>
    </select>

    
</div>
                <input type="submit" value="Editar">
            </form>
        </div>
    <?php endif ?>