<?php if (isset($_SESSION['USER_ID'])) : ?>
    <form action="agregarServicio" method="POST" class="my-4">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label>ID SERVICIO STREAMING</label>
                    <input required name="id_servicio_streaming" type="number" class="form-control">
                </div>
                <div class="form-group">
                    <label>Nombre</label>
                    <input required name="nombre" type="text" class="form-control">
                    <div>
                    <button type="submit" class="btn btn-outline-success d-grid gap-2 col-6 mx-auto my-4">Guardar</button>
                    </div>
    </form>
    
<?php else : ?>
 
    <form action="login" method="POST" class="my-4">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label>ID SERVICIO STREAMING</label>
                    <input required name="id_servicio_streaming" type="number" class="form-control">
                </div>
                <div class="form-group">
                    <label>Nombre</label>
                    <input required name="nombre" type="text" class="form-control">
                    <div>
                    <button type="submit" class="btn btn-outline-success d-grid gap-2 col-6 mx-auto my-4">Guardar</button>
                    </div>
                    <?php endif ?>