<?php require 'app/templates/header.phtml' ?>

<div class="container mt-5 w-25 mx-auto">
    <form method="POST" action="auth">
        <div class="form-group mb-4">
            <label class="form-label"  for="username">Usuario</label>
            <input class="form-control" type="username" id="username" name="username" aria-describedby="emailHelp">
        </div>
        <div class="form-group mb-4">
            <label class="form-label" for="password">Password</label>
            <input class="form-control" type="password" id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div>
        <?php endif ?>
        <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary btn btn-secondary">Entrar</button>
        </div>
    </form>
</div>