<?php require 'app/templates/header.phtml' ?>



<table class="table tabble-stripped text-center">
    <tr class="table-primary">
        <th>Nombre</th>
        <th>Director</th>
        <th>Servicio Streaming</th>
        <th>Tipo</th>
        <th>Género</th>
    </tr>
    <?php foreach ($peliculas as $pelicula ) { ?>
        <tr>
            <td class="table-light"><?php echo $pelicula->nombre ?></td>
            <td class="table-light"><?php echo $pelicula->director ?></td>
            <td class="table-light"><?php echo $pelicula->nombre_servicio ?></td>
          
            <td class="table-light"><?php echo $pelicula->tipo ?></td>
            <td class="table-light"> <?php echo $pelicula->genero ?></td>
        </tr>
        
    <?php } ?>
   
</table>