<?php require 'app/templates/header.phtml' ?>
<div class="container d-flex justify-content-center">
<table class="table tabble-stripped text-center">
<tr class="table-primary">
        <th>Nombre</th>
        <th>ID</th>
    </tr>
    <?php foreach ($servicios as $s) { ?>
        <tr>
        <td class="table-light"><?php echo $s->nombre ?></td>
        <td class="table-light"><?php echo $s->id_servicio_streaming ?></td>
        </tr>
    <?php } ?>
</table>
</div>