<?php require 'app/templates/agregarServicio.phtml' ?>
<ul class="list-group">
    
<?php foreach ($servicios as $s) : ?>
        <div class="table-light d-flex justify-content-between">
            <table class="table">
            <td><a href='viewServicio/<?= $s->id_servicio_streaming?>'>
                            <?= $s->nombre?> (ID: <?= $s->id_servicio_streaming ?>)
                        </a>
                </table>
                <?php if (!isset($_SESSION['USER_ID'])) : ?>

                <?php else : ?>
                    <div class="actions">
                        <a href="deleteServicio/<?= $s->id_servicio_streaming ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                    </div>

          
                    
        <?php endif ?>
        </div>
    <?php endforeach ?>
    </ul>
</ul>
</div>
</form>
<?php require 'app/templates/editarServicio.phtml' ?>
    <p class="mt-3"><small>Mostrando <?= $count ?> Servicios</small></p>